### ISSUE TITLE
Could you bump versions for 2.11?

### ISSUE THREAD

**Issue by tonicebrian** [gnieh/gnieh-pp#1]
It would be nice if compiled versions for Scala 2.11 could be uploaded to Maven Central since we are evaluating using this library in our projects.

**Comment by satabin** [comment]
Hi,

I should have mentioned it but this library has been integrated in [tekstlib](https://github.com/gnieh/tekstlib) which exists for both 2.11 and 2.12. I recommend you to evaluate using the tekstlib library instead and report potential problems there.

**Comment by tonicebrian** [comment]
Thanks. I've created a PR to add info for using your project. Is there any stable release planned for publishing in Sonatype?

**Comment by satabin** [comment]
I had hoipe to have a more complete version before making a first stable release, but I have no time to work on it right now. The current library is stable enough for a 0.1.0 release and will make it complete in the coming week.
